# Generated by Django 2.1.2 on 2019-01-19 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=15)),
                ('added_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('query', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=6536, null=True)),
            ],
        ),
    ]
