# Generated by Django 2.1.2 on 2019-01-19 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackQuiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioncache',
            name='site',
            field=models.CharField(default=0, max_length=55),
            preserve_default=False,
        ),
    ]
